services:
  postgres:
    image: postgres:15.17
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: "sub_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d sub_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - sub_service_net

  sub_service:
    image: sub_service:latest
    container_name: sub_service
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - sub_service_net

networks:
  sub_service_net:
    name: sub_service_net
    driver: bridge