### CREATE
# curl -X POST http://localhost:8080/subscriptions
#  -H "Content-Type: application/json"
#  -d '{
#    "service_name": "Yandex Plus",
#    "price": 400,
#    "user_id": "60601fee-2bf1-4721-ae6f-7636e79a0cba",
#    "start_date": "07-2025"
#  }'
POST http://localhost:8080/subscriptions
Content-Type: application/json

{
  "service_name": "Yandex Plus",
  "price": 400,
  "user_id": "60601fee-2bf1-4721-ae6f-7636e79a0cba",
  "start_date": "07-2025",
  "end_date": "08-2025"
}

### GetByID
# curl http://localhost:8080/subscriptions/2d33c59e-f4b9-414b-a0c3-36b48772bb69
GET http://localhost:8080/subscriptions/2d33c59e-f4b9-414b-a0c3-36b48772bb69

### LIST
# curl "http://localhost:8080/subscriptions"
GET http://localhost:8080/subscriptions

### LIST with limit and offset
# curl "http://localhost:8080/subscriptions?limit=5&offset=0"
GET http://localhost:8080/subscriptions?limit=3&offset=0

### LIST with user_id
# curl "http://localhost:8080/subscriptions?user_id=60601fee-2bf1-4721-ae6f-7636e79a0cba"
GET http://localhost:8080/subscriptions?user_id=60601fee-2bf1-4721-ae6f-7636e79a0cba

### LIST with service_name
# curl "http://localhost:8080/subscriptions?service_name=Yandex Plus"
GET http://localhost:8080/subscriptions?service_name=Yandex Plus

### UPDATE
# curl -X PUT http://localhost:8080/subscriptions/2d33c59e-f4b9-414b-a0c3-36b48772bb69 \
#  -H "Content-Type: application/json" \
#  -d '{
#    "service_name": "Netflix",
#    "price": 999,
#    "user_id": "60601fee-2bf1-4721-ae6f-7636e79a0cba",
#   "start_date": "07-2025",
#    "end_date": "09-2025"
#  }'
PUT http://localhost:8080/subscriptions/2d33c59e-f4b9-414b-a0c3-36b48772bb69
Content-Type: application/json

{
  "service_name": "Netflix",
  "price": 999,
  "user_id": "60601fee-2bf1-4721-ae6f-7636e79a0cba",
  "start_date": "07-2025",
  "end_date": "09-2025"
}

### DELETE
# curl -X DELETE http://localhost:8080/subscriptions/fe04b550-07fc-4d01-82fc-07ed878675a8 -i
DELETE http://localhost:8080/subscriptions/fe04b550-07fc-4d01-82fc-07ed878675a8

### CalculateTotalPrice only by dates
# curl "http://localhost:8080/subscriptions/total?from=01-2025&to=12-2025"
GET http://localhost:8080/subscriptions/total?from=01-2025&to=08-2025

### CalculateTotalPrice with user_id and service_name
# curl "http://localhost:8080/subscriptions/total?from=01-2025&to=12-2025&user_id=60601fee-2bf1-4721-ae6f-7636e79a0cba&service_name=Yandex Plus"
GET http://localhost:8080/subscriptions/total?from=01-2025&to=12-2025&user_id=60601fee-2bf1-4721-ae6f-7636e79a0cba&service_name=Yandex Plus