### curl -X POST http://localhost:8080/subscriptions
#  -H "Content-Type: application/json"
#  -d '{
#    "service_name": "Yandex Plus",
#    "price": 400,
#    "user_id": "60601fee-2bf1-4721-ae6f-7636e79a0cba",
#    "start_date": "07-2025"
#  }'
POST http://localhost:8080/subscriptions
Content-Type: application/json

{
  "service_name": "Yandex Plus",
  "price": 400,
  "user_id": "60601fee-2bf1-4721-ae6f-7636e79a0cba",
  "start_date": "07-2025",
  "end_date": "08-2025"
}

### curl http://localhost:8080/subscriptions/5383e26e-6515-42be-b6df-519b0c6741f7
GET http://localhost:8080/subscriptions/5383e26e-6515-42be-b6df-519b0c6741f7

### curl "http://localhost:8080/subscriptions"
GET http://localhost:8080/subscriptions

### curl "http://localhost:8080/subscriptions?limit=5&offset=0"
GET http://localhost:8080/subscriptions?limit=3&offset=0

### curl "http://localhost:8080/subscriptions?user_id=60601fee-2bf1-4721-ae6f-7636e79a0cba"
GET http://localhost:8080/subscriptions?user_id=60601fee-2bf1-4721-ae6f-7636e79a0cba

### curl "http://localhost:8080/subscriptions?service_name=Yandex Plus"
GET http://localhost:8080/subscriptions?service_name=Yandex Plus

### curl -X PUT http://localhost:8080/subscriptions/b7402536-5a55-4ee8-a0a6-e42de4d76f54 \
#  -H "Content-Type: application/json" \
#  -d '{
#    "service_name": "Netflix",
#    "price": 999,
#    "user_id": "60601fee-2bf1-4721-ae6f-7636e79a0cba",
#   "start_date": "07-2025",
#    "end_date": "09-2025"
#  }'
PUT http://localhost:8080/subscriptions/b7402536-5a55-4ee8-a0a6-e42de4d76f54
Content-Type: application/json

{
  "service_name": "Netflix",
  "price": 999,
  "user_id": "60601fee-2bf1-4721-ae6f-7636e79a0cba",
  "start_date": "07-2025",
  "end_date": "09-2025"
}

### curl -X DELETE http://localhost:8080/subscriptions/7bd8b793-103c-4370-95db-4fbfdfaf9c50 -i
DELETE http://localhost:8080/subscriptions/7bd8b793-103c-4370-95db-4fbfdfaf9c50